accounts/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.urls import path 

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('users/delete', views.user_delete_view, name='user_delete_view'),
    path('users/', views.user_view, name='user_view'),
]

main_app/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.urls import path 
from . import views

app_name = 'main_app'

urlpatterns = [
    re_path(r'^$', views.index,name='index'),
    re_path(r'^client/edit/',views.client_edit_view,name='client_edit_view'),
    re_path(r'^client/delete/',views.client_delete_view,name='client_delete_view'),
    re_path(r'^client/',views.client_view,name='client_view'),
    re_path(r'^personnel/edit/',views.personnel_edit_view,name='personnel_edit_view'),
    re_path(r'^personnel/delete/',views.personnel_delete_view,name='personnel_delete_view'),
    re_path(r'^personnel/',views.personnel_view,name='personnel_view'),
    re_path(r'^produit/edit/',views.produit_edit_view,name='produit_edit_view'),
    re_path(r'^produit/delete/',views.produit_delete_view,name='produit_delete_view'),
    re_path(r'^produit/',views.produit_view,name='produit_view'),
    re_path(r'^profil/edit/',views.profil_edit_view,name='profil_edit_view'),
    re_path(r'^profil/delete/',views.profil_delete_view,name='profil_delete_view'),
    re_path(r'^profil/',views.profil_view,name='profil_view'),
    re_path(r'^machine/edit/',views.machine_edit_view,name='machine_edit_view'),
    re_path(r'^machine/delete/',views.machine_delete_view,name='machine_delete_view'),
    re_path(r'^machine/',views.machine_view,name='machine_view'),
    re_path(r'^bois/edit/',views.bois_edit_view,name='bois_edit_view'),
    re_path(r'^bois/delete/',views.bois_delete_view,name='bois_delete_view'),
    re_path(r'^bois/',views.bois_view,name='bois_view'),
    re_path(r'^production/edit/',views.production_edit_view,name='production_edit_view'),
    re_path(r'^production/delete/',views.production_delete_view,name='production_delete_view'),
    re_path(r'^production/',views.production_view,name='production_view'),
    re_path(r'^fournisseur/edit/',views.fournisseur_edit_view,name='fournisseur_edit_view'),
    re_path(r'^fournisseur/delete/',views.fournisseur_delete_view,name='fournisseur_delete_view'),
    re_path(r'^fournisseur/',views.fournisseur_view,name='fournisseur_view'),
    re_path(r'^achat/edit/',views.achat_edit_view,name='achat_edit_view'),
    re_path(r'^achat/delete/',views.achat_delete_view,name='achat_delete_view'),
    re_path(r'^achat/',views.achat_view,name='achat_view'),
    re_path(r'^commande/edit/',views.commande_edit_view,name='commande_edit_view'),
    re_path(r'^commande/delete/',views.commande_delete_view,name='commande_delete_view'),
    re_path(r'^commande/detail/(?P<commande_id>[0-9])',views.commande_detail_view,name='commande_detail_view'),
    re_path(r'^commande/produit/delete/',views.commande_produit_delete_view,name='commande_produit_delete_view'),
    re_path(r'^commande/produit/edit/',views.commande_produit_edit_view,name='commande_produit_edit_view'),
    re_path(r'^commande/produit/create/',views.commande_produit_create_view,name='commande_produit_create_view'),
    re_path(r'^commande/',views.commande_view,name='commande_view'),

]

woodapp_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path
from main_app import views as main_app_views 
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls), 
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^', include('main_app.urls')),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

main_app/models.py
from django.db import models

# Create your models here.

class Service(models.Model):
    nom_service = models.CharField(max_length=254)
    def __str__(self):
        return self.nom_service

class Banque(models.Model):
    numero_compte = models.CharField(max_length=254)
    nom = models.CharField(max_length=254)
    prenoms = models.CharField(max_length=254)
    tel = models.CharField(max_length=254)
    def __str__(self):
        return self.nom + self.prenoms

class Profil(models.Model):
    nom = models.CharField(max_length=254)
    def __str__(self):
        return self.nom

class Personnel(models.Model):
    nom = models.CharField(max_length=254)
    prenoms = models.CharField(max_length=254)
    adresse = models.CharField(max_length=254)
    num_compte = models.CharField(max_length=254)
    profil = models.ForeignKey(Profil, on_delete=models.CASCADE)
    def __str__(self):
        return self.nom +" "+ self.prenoms

class Client(models.Model):
    nom_client = models.CharField(max_length=254)
    prenom_client = models.CharField(max_length=254)
    num_compte = models.CharField(max_length=254)
    def __str__(self):
        return self.nom_client +' '+ self.prenom_client

class Fournisseur(models.Model):
    nom_four = models.CharField(max_length=254)
    tel_four = models.CharField(max_length=254)
    adresse_four = models.CharField(max_length=254)
    num_compte = models.CharField(max_length=254)
    def __str__(self):
        return self.nom_four

class Machine(models.Model):
    usage = models.CharField(max_length=254)
    responsable = models.ForeignKey(Personnel, on_delete=models.CASCADE)
    def __str__(self):
        return self.usage

class TypeMatiere(models.Model):
    nom = models.CharField(max_length=254)
    def __str__(self):
        return self.nom

class ProduitFini(models.Model):
    type_produit = models.CharField(max_length=254)
    def __str__(self):
        return self.type_produit

class Commande(models.Model):
    type_commande = models.CharField(max_length=254)
    date_commande = models.CharField(max_length=254)
    date_livr_commande = models.CharField(max_length=254, null =True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    def __str__(self):
        return self.num_commande

class Commercial(models.Model):
    num_agent_commer = models.CharField(max_length=254)
    def __str__(self):
        return self.num_commande

class ProduitCommande(models.Model):
    commande = models.ForeignKey(Commande, on_delete=models.CASCADE)
    produit = models.ForeignKey(ProduitFini, on_delete=models.CASCADE)
    quantite = models.IntegerField()
    def __str__(self):
        return self.num_commande

class Production(models.Model):
    produit = models.ForeignKey(ProduitFini, on_delete=models.CASCADE)
    quantite = models.IntegerField()
    date_production = models.CharField(max_length=254)
    def __str__(self):
        return self.produit.type_produit+ " ("+ self.quantite +")"

class Achat(models.Model):
    bois = models.ForeignKey(TypeMatiere, on_delete=models.CASCADE)
    fournisseur = models.ForeignKey(Fournisseur, on_delete=models.CASCADE)
    quantite = models.IntegerField()
    date_achat = models.CharField(max_length=254)
    def __str__(self):
        return self.bois.nom+ " ("+ self.quantite +")"

main_app/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponse 
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required 
import datetime
from django.contrib.auth.forms import UserCreationForm
from main_app.models import *
from main_app.forms import *
from django.http import JsonResponse
from django.core import serializers



@login_required
def commande_view(request):
	if request.method == "POST":
		form = CommandeForm(data=request.POST)
		if form.is_valid():
			instance = Commande()
			client_id= request.POST.get('client')
			client = Client.objects.get(id=client_id)
			instance.type_commande = request.POST.get('type_commande')
			instance.date_commande = request.POST.get('date_commande')
			instance.date_livr_commande = request.POST.get('date_livr_commande')
			instance.client= client
			instance.save()
		else :
			print(form.errors)

	else :
		form = CommandeForm()
	list_instances= Commande.objects.all()
	list_clients= Client.objects.all()

	return render(request,'main_app/commande_all.html', 
							{'list_instances':list_instances,
							'list_clients':list_clients,
							'form':form
							})
@login_required
def commande_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = Commande.objects.get(id=data_id) 
	instance.delete()
	return redirect('main_app:commande_view')

@login_required
def commande_produit_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = ProduitCommande.objects.get(id=data_id) 	
	commande_id= instance.commande.id
	instance.delete()
	return redirect('main_app:commande_detail_view',commande_id=commande_id )

@login_required
def commande_detail_view(request, commande_id):
	commande = Commande.objects.get(id=commande_id)
	list_instances= ProduitCommande.objects.filter(commande=commande_id)
	list_produits= ProduitFini.objects.all()
	form = ProduitCommandeForm()
	return render(request,'main_app/commande_detail.html', 
							{'commande':commande,
							 'list_instances':list_instances,
							 'list_produits':list_produits,
							 'form':form
							})


@login_required
def commande_produit_create_view(request):
	if request.method == "POST":
		form = ProduitCommandeForm(data=request.POST)
		commande_id = request.POST.get('commande_id')
		commande= Commande.objects.get(id=commande_id)
		if form.is_valid():
			instance = ProduitCommande()
			produit_id = request.POST.get('produit')
			produit = ProduitFini.objects.get(id=produit_id)
			instance.produit= produit
			instance.commande= commande
			instance.quantite = request.POST.get('quantite')
			instance.save()
		else :
			print(form.errors)

	else :
		form = ProduitCommandeForm()
	list_instances= ProduitCommande.objects.filter(commande=commande_id)
	list_produits= ProduitFini.objects.all()
	return render(request,'main_app/commande_detail.html', 
							{'commande':commande,
							 'list_instances':list_instances,
							 'list_produits':list_produits,
							 'form':form,
							})

@login_required
def commande_produit_edit_view(request):
	if request.method == "POST":
		form = ProduitCommandeForm(data=request.POST)
		if form.is_valid():
			id = request.POST.get('id')
			produit_id = request.POST.get('produit')
			produit = ProduitFini.objects.get(id=produit_id)
			instance = ProduitCommande.objects.get(id=id)
			instance.quantite = request.POST.get('quantite')
			instance.produit= produit
			instance.save()
			return redirect('main_app:commande_detail_view',commande_id=instance.commande.id )
		else :
			print('Form erros')

@login_required
def commande_edit_view(request):
	if request.method == "POST":
		commandeForm = CommandeForm(data=request.POST)
		if commandeForm.is_valid():
			id = request.POST.get('id')
			instance = Commande.objects.get(id=id)
			instance.type_commande = request.POST.get('type_commande')
			instance.date_commande = request.POST.get('date_commande')
			instance.date_livr_commande = request.POST.get('date_livr_commande')
			instance.save()
			return redirect('main_app:commande_view')
		else :
			print('Form erros')

@login_required
def achat_view(request):
	if request.method == "POST":
		form =AchatForm(data=request.POST)
		if form.is_valid():
			instance = Achat()
			bois_id= request.POST.get('bois')
			bois = TypeMatiere.objects.get(id=bois_id)
			fournisseur_id= request.POST.get('fournisseur')
			fournisseur = Fournisseur.objects.get(id=fournisseur_id)
			instance.quantite = request.POST.get('quantite')
			instance.date_achat = request.POST.get('date_achat')
			instance.bois = bois
			instance.fournisseur = fournisseur
			instance.save()
		else :
			print(form.errors)

	else :
		form = AchatForm()
	list_instances= Achat.objects.all()
	list_bois= TypeMatiere.objects.all()
	list_fournisseurs= Fournisseur.objects.all()

	return render(request,'main_app/achat_all.html', 
							{'list_instances':list_instances,
							'list_bois':list_bois,
							'list_fournisseurs':list_fournisseurs,
							'form':form
							})
@login_required
def achat_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = Achat.objects.get(id=data_id) 
	instance.delete()
	return redirect('main_app:achat_view')

@login_required
def achat_edit_view(request):
	if request.method == "POST":
		achatForm = AchatForm(data=request.POST)
		if achatForm.is_valid():
			id = request.POST.get('id')
			bois_id= request.POST.get('bois')
			bois = TypeMatiere.objects.get(id=bois_id)
			fournisseur_id= request.POST.get('fournisseur')
			fournisseur = Fournisseur.objects.get(id=fournisseur_id)
			instance = Achat.objects.get(id=id)
			instance.quantite = request.POST.get('quantite')
			instance.date_achat = request.POST.get('date_achat')
			instance.bois = bois
			instance.fournisseur = fournisseur
			instance.save()
			return redirect('main_app:achat_view')
		else :
			print('Form erros')

@login_required
def fournisseur_view(request):
	if request.method == "POST":
		form = FournisseurForm(data=request.POST)
		if form.is_valid():
			instance = Fournisseur()
			instance.nom_four = request.POST.get('nom_four')
			instance.tel_four = request.POST.get('tel_four')
			instance.adresse_four = request.POST.get('adresse_four')
			instance.num_compte = request.POST.get('num_compte')
			instance.save()
		else :
			print(form.errors)

	else :
		form = FournisseurForm()
	list_instances= Fournisseur.objects.all()

	return render(request,'main_app/fournisseur_all.html', 
							{'list_instances':list_instances,
							'form':form
							})
@login_required
def fournisseur_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = Fournisseur.objects.get(id=data_id) 
	instance.delete()
	return redirect('main_app:fournisseur_view')

@login_required
def fournisseur_edit_view(request):
	if request.method == "POST":
		fournisseurForm = FournisseurForm(data=request.POST)
		if fournisseurForm.is_valid():
			id = request.POST.get('id')
			instance = Fournisseur.objects.get(id=id)
			instance.nom_four = request.POST.get('nom_four')
			instance.tel_four = request.POST.get('tel_four')
			instance.adresse_four = request.POST.get('adresse_four')
			instance.num_compte = request.POST.get('num_compte')
			instance.save()
			return redirect('main_app:fournisseur_view')
		else :
			print('Form erros')


@login_required
def production_view(request):
	if request.method == "POST":
		form = ProductionForm(data=request.POST)
		if form.is_valid():
			instance = Production()
			produit_id= request.POST.get('produit')
			produit = ProduitFini.objects.get(id=produit_id)
			instance.quantite = request.POST.get('quantite')
			instance.date_production = request.POST.get('date_production')
			instance.produit = produit
			instance.save()
		else :
			print(form.errors)

	else :
		form = ProductionForm()
	list_instances= Production.objects.all()
	list_produits= ProduitFini.objects.all()

	return render(request,'main_app/production_all.html', 
							{'list_instances':list_instances,
							'list_produits':list_produits,
							'form':form
							})
@login_required
def production_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = Production.objects.get(id=data_id) 
	instance.delete()
	return redirect('main_app:production_view')

@login_required
def production_edit_view(request):
	if request.method == "POST":
		productionForm = ProductionForm(data=request.POST)
		if productionForm.is_valid():
			id = request.POST.get('id')
			produit_id= request.POST.get('produit')
			produit = ProduitFini.objects.get(id=produit_id)
			instance = Production.objects.get(id=id)
			instance.quantite = request.POST.get('quantite')
			instance.date_production = request.POST.get('date_production')
			instance.produit = produit
			instance.save()
			return redirect('main_app:production_view')
		else :
			print('Form erros')


@login_required
def bois_view(request):
	if request.method == "POST":
		form = TypeMatiereForm(data=request.POST)
		if form.is_valid():
			instance = TypeMatiere()
			instance.nom = request.POST.get('nom')
			instance.save()
		else :
			print(form.errors)

	else :
		form = TypeMatiereForm()
	list_instances= TypeMatiere.objects.all()

	return render(request,'main_app/bois_all.html', 
							{'list_instances':list_instances,
							'form':form
							})
@login_required
def bois_delete_view(request):
	data_id = request.POST.get('data_id')	
	instance = TypeMatiere.objects.get(id=data_id) 
	instance.delete()
	return redirect('main_app:bois_view')

@login_required
def bois_edit_view(request):
	if request.method == "POST":
		typeMatiereForm = TypeMatiereForm(data=request.POST)
		if typeMatiereForm.is_valid():
			id = request.POST.get('id')
			instance = TypeMatiere.objects.get(id=id)
			instance.nom = request.POST.get('nom')
			instance.save()
			return redirect('main_app:bois_view')
		else :
			print('Form erros')

@login_required

main_app/templates/main_app/client_all.html
{% extends 'main_app/layout/base.html' %}
{% load static %}
{% block content %}

<div class="bg-white mb-5 pb-5 mt-2">
<div class="row mt-2 pt-2 m-2">
	<div class="col-sm-8">
		<h2>Gestion des clients</h2>
	</div>
	<div class="col-sm-4">
		<button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#additem"  >Nouveau  client</button>
	</div>
</div>	 
<div class="row justify-content-center m-1    ">
	 <div class="col-sm-12 table-responsive">
	 	<table class="table table-bordered">
		  <thead class="bg-dark text-white">
		    <tr> 
		      <!-- <th scope="col">#</th> -->
		      <th scope="col">Nom   </th>
		      <th scope="col">Prénom   </th>
		      <th scope="col">Numéro compte</th>
		      <th scope="col">Actions</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for item in list_instances %}

		    <tr> 
		      <td>{{ item.nom_client }}</td>
		      <td>{{ item.prenom_client }}</td>
		      <td>{{ item.num_compte }}</td> 
		      <td>
				<a href="#" rel="tooltip" class="btn btn-info btn-sm btn-round" data-toggle="modal" data-target="#edit_item_{{item.id}}" >
					                    <i class="material-icons">edit</i>
				</a>


					                
				<button type="button" rel="tooltip" class="btn btn-danger btn-sm btn-round"  onclick="event.preventDefault();
                              document.getElementById('form_item_{{item.id}}').submit();" >
					                    <i class="material-icons">close</i>
				</button>
					                
                <form id="form_item_{{item.id}}" action="{% url 'main_app:client_delete_view' %}" method="POST" style="display: none;">
                                        {% csrf_token %} 
                                        <input type="text" hidden class="form-control"  name="data_id" value="{{item.id}}" >
                </form>      	 
		      </td> 
		    </tr> 



		    <div class="modal fade" id="edit_item_{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
					  <div class="modal-dialog modal-lg" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        <h5 class="modal-title" id="exampleModalLabel">Modification d'un client</h5>
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
					          <span aria-hidden="true">&times;</span>
					        </button>
					      </div>
					      <div class="modal-body">
					        <form action="{% url 'main_app:client_edit_view' %}" method="POST" enctype="multipart/form-data" >
							    {% csrf_token %}  

							    	<div class="row mt-1">
							    		<div class="col-sm-6">
							                  <label class="form-control-label">Nom </label> 
							                <div class="form-group">
 													<input type="text" name="nom_client" class="form-control" value="{{item.nom_client}}">
 													<input type="numeric" name="id" hidden class="form-control" value="{{item.id}}">
							                </div>
							    			
							    		</div>
							    		<div class="col-sm-6">
							                  <label class="form-control-label">Prénom</label> 
							                <div class="form-group">
 													<input type="text" name="prenom_client" class="form-control" value="{{item.prenom_client}}"> 
							                </div>
							    			
							    		</div>
							    		<div class="col-sm-6">
							                  <label class="form-control-label">Numéro de compte</label> 
							                <div class="form-group">
 													<input type="text" name="num_compte" class="form-control" value="{{item.num_compte}}"> 
							                </div>							    			
							    		</div>
							    		   
							    	</div>  
							    <div class="row mt-1 pt-1">
							    	<div class="col-sm-4">
							    		
					        			<button type="submit" class="btn btn-info">Enregistrer</button>
							    	</div>
							    </div>


							</form>
					      </div> 
					    </div>
					  </div>
					</div>

		    {% endfor %}
		  </tbody>
		</table>
	 </div> 

</div>
</div>





<div class="modal fade" id="additem" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ajout d'un client</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'main_app:client_view' %}" method="POST" enctype="multipart/form-data" >
		    {% csrf_token %} 

		    	<div class="row mt-1">

		    {% for field in form  %}

		    		<div class="col-sm-6">
		                  <label class="form-control-label">{{ field.label }}</label> 
		                <div class="form-group">

		                    {{ field  }}
		                    <!-- {% if field.help_text %}
		                    <p class="help">{{ field.help_text|safe }}</p>
		                    {% endif %} -->
		                    <div class="{% if field.errors %} invalid{% endif %}">
		                      {% for error in field.errors %}
		                      <p class="help-block">{{ error }}</p>
		                      {% endfor %}
		                    </div> 
		                </div>
		    			
		    		</div>
		    {% endfor %} 
		    	</div> 
		    <div class="row mt-1 pt-1">
		    	<div class="col-sm-4">
		    		
        			<button type="submit" class="btn btn-info">Enregistrer</button>
		    	</div>
		    </div>


		</form>
      </div> 
    </div>
  </div>
</div>


{% endblock %}

main_app/templates/main_app/commande_detail.html
{% extends 'main_app/layout/base.html' %}
{% load static %}
{% block content %}

<div class="bg-white mb-5 ">
	<div class="row    m-2">
		<div class="col-sm-8">
			<h2>Gestion des commandes</h2>
		</div> 
	</div>	 
	<div class="row justify-content-center m-1    ">
		<div class="col-sm-12 table-responsive">
			<table class="table table-bordered">
			<thead class="bg-secondary text-white">
				<tr> 
				<!-- <th scope="col">#</th> -->
				<th scope="col">Numéro commande   </th>
				<th scope="col">Type commande   </th>
				<th scope="col">Date commande   </th> 
				<th scope="col">Date livraison   </th> 
				</tr>
			</thead>
			<tbody> 

				<tr> 
				<td>{{ commande.id }}</td>
				<td>{{ commande.type_commande }}</td>
				<td>{{ commande.date_commande }}</td>
				<td>{{ commande.date_livr_commande }}</td>  
				</tr>  

			</tbody>
			</table>
		</div> 

	</div>
	<hr/>
	
	<div class="row  mt-3 m-2">
		<div class="col-sm-8">
			<p> <strong> Produits commandés </strong> </p>
		</div>
		<div class="col-sm-4">
			<button type="button" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#additem"  >Ajouter un produit</button>
		</div>
	</div>
		 
	<div class="row justify-content-center m-1    ">
		<div class="col-sm-12 table-responsive">
			<table class="table table-bordered">
			<thead class="bg-dark text-white">
				<tr> 
				<!-- <th scope="col">#</th> -->
				<th scope="col">Type produit   </th>
				<th scope="col">Quantité   </th>
				<th scope="col">Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for item in list_instances %}

				<tr> 
				<td>{{ item.produit.type_produit }}</td>
				<td>{{ item.quantite }}</td>
				<td>
					<a href="#" rel="tooltip" class="btn btn-info btn-sm btn-round" data-toggle="modal" data-target="#edit_item_{{item.id}}" >
											<i class="material-icons">edit</i>
					</a>
										
					<button type="button" rel="tooltip" class="btn btn-danger btn-sm btn-round"  onclick="event.preventDefault();
								document.getElementById('form_item_{{item.id}}').submit();" >
											<i class="material-icons">close</i>
					</button>
										
					<form id="form_item_{{item.id}}" action="{% url 'main_app:commande_produit_delete_view' %}" method="POST" style="display: none;">
											{% csrf_token %} 
											<input type="text" hidden class="form-control"  name="data_id" value="{{item.id}}" >
					</form>      	 
				</td> 
				</tr> 



				<div class="modal fade" id="edit_item_{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
	aria-hidden="true">
						<div class="modal-dialog modal-lg" role="document">
							<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="exampleModalLabel">Modification d'un produi commandé</h5>
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">
								<form action="{% url 'main_app:commande_produit_edit_view' %}" method="POST" enctype="multipart/form-data" >
									{% csrf_token %}  

										<div class="row mt-1">

											
							    		<div class="col-sm-6">      
											<div class="form-goup">         
												<label for="">Produit</label>
 													
													<select class="form-control " data-style="btn btn-link"   name="produit"  required >
														{% for data in list_produits %}
															<option value={{data.id}} {% if data.id == item.produit.id %} selected  {% endif %} > {{data.type_produit}}  </option> 
														{% endfor %}
													</select>												
											</div>
							    			
							    		</div>
											<div class="col-sm-6">
												<label class="form-control-label">Quantité	</label> 
												<div class="form-group">
														<input type="numeric" name="id" hidden class="form-control" value="{{item.id}}">
														<input type="text" name="quantite" class="form-control " value="{{item.quantite}}"> 
												</div>
												
											</div> 
											
										</div>  
									<div class="row mt-1 pt-1">
										<div class="col-sm-4">
											
											<button type="submit" class="btn btn-info">Enregistrer</button>
										</div>
									</div>


								</form>
							</div> 
							</div>
						</div>
						</div>

				{% endfor %}
			</tbody>
			</table>
		</div> 

	</div>


	




</div>





<div class="modal fade" id="additem" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ajout d'un produit commandé</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'main_app:commande_produit_create_view' %}" method="POST" enctype="multipart/form-data" >
		    {% csrf_token %} 

		    	<div class="row mt-1">
				<div class="form-group">
 					<input type="numeric" name="commande_id" hidden class="form-control" value="{{commande.id}}">
				</div>
		    {% for field in form  %}

		    		<div class="col-sm-6">
		                  <label class="form-control-label">{{ field.label }}</label> 
		                <div class="form-group">

		                    {{ field  }}
		                    <div class="{% if field.errors %} invalid{% endif %}">
		                      {% for error in field.errors %}
		                      <p class="help-block">{{ error }}</p>
		                      {% endfor %}
		                    </div> 
		                </div>
		    			
		    		</div>
		    {% endfor %} 
		    	</div> 
		    <div class="row mt-1 pt-1">
		    	<div class="col-sm-4">
		    		
        			<button type="submit" class="btn btn-info">Enregistrer</button>
		    	</div>
		    </div>


		</form>
      </div> 
    </div>
  </div>
</div>


{% endblock %}