accounts/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.urls import path 

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('users/delete', views.user_delete_view, name='user_delete_view'),
    path('users/', views.user_view, name='user_view'),
]

main_app/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.urls import path 
from . import views

app_name = 'main_app'

urlpatterns = [
    re_path(r'^$', views.index,name='index'),
    re_path(r'^client/edit/',views.client_edit_view,name='client_edit_view'),
    re_path(r'^client/delete/',views.client_delete_view,name='client_delete_view'),
    re_path(r'^client/',views.client_view,name='client_view'),
    re_path(r'^personnel/edit/',views.personnel_edit_view,name='personnel_edit_view'),
    re_path(r'^personnel/delete/',views.personnel_delete_view,name='personnel_delete_view'),
    re_path(r'^personnel/',views.personnel_view,name='personnel_view'),
    re_path(r'^produit/edit/',views.produit_edit_view,name='produit_edit_view'),
    re_path(r'^produit/delete/',views.produit_delete_view,name='produit_delete_view'),
    re_path(r'^produit/',views.produit_view,name='produit_view'),
    re_path(r'^profil/edit/',views.profil_edit_view,name='profil_edit_view'),
    re_path(r'^profil/delete/',views.profil_delete_view,name='profil_delete_view'),
    re_path(r'^profil/',views.profil_view,name='profil_view'),
    re_path(r'^machine/edit/',views.machine_edit_view,name='machine_edit_view'),
    re_path(r'^machine/delete/',views.machine_delete_view,name='machine_delete_view'),
    re_path(r'^machine/',views.machine_view,name='machine_view'),
    re_path(r'^bois/edit/',views.bois_edit_view,name='bois_edit_view'),
    re_path(r'^bois/delete/',views.bois_delete_view,name='bois_delete_view'),
    re_path(r'^bois/',views.bois_view,name='bois_view'),
    re_path(r'^production/edit/',views.production_edit_view,name='production_edit_view'),
    re_path(r'^production/delete/',views.production_delete_view,name='production_delete_view'),
    re_path(r'^production/',views.production_view,name='production_view'),
    re_path(r'^fournisseur/edit/',views.fournisseur_edit_view,name='fournisseur_edit_view'),
    re_path(r'^fournisseur/delete/',views.fournisseur_delete_view,name='fournisseur_delete_view'),
    re_path(r'^fournisseur/',views.fournisseur_view,name='fournisseur_view'),
    re_path(r'^achat/edit/',views.achat_edit_view,name='achat_edit_view'),
    re_path(r'^achat/delete/',views.achat_delete_view,name='achat_delete_view'),
    re_path(r'^achat/',views.achat_view,name='achat_view'),
    re_path(r'^commande/edit/',views.commande_edit_view,name='commande_edit_view'),
    re_path(r'^commande/delete/',views.commande_delete_view,name='commande_delete_view'),
    re_path(r'^commande/detail/(?P<commande_id>[0-9])',views.commande_detail_view,name='commande_detail_view'),
    re_path(r'^commande/produit/delete/',views.commande_produit_delete_view,name='commande_produit_delete_view'),
    re_path(r'^commande/produit/edit/',views.commande_produit_edit_view,name='commande_produit_edit_view'),
    re_path(r'^commande/produit/create/',views.commande_produit_create_view,name='commande_produit_create_view'),
    re_path(r'^commande/',views.commande_view,name='commande_view'),

]

woodapp_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path
from main_app import views as main_app_views 
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls), 
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^', include('main_app.urls')),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

main_app/models.py
from django.db import models

# Create your models here.

class Service(models.Model):
    nom_service = models.CharField(max_length=254)
    def __str__(self):
        return self.nom_service

class Banque(models.Model):
    numero_compte = models.CharField(max_length=254)
    nom = models.CharField(max_length=254)
    prenoms = models.CharField(max_length=254)
    tel = models.CharField(max_length=254)
    def __str__(self):
        return self.nom + self.prenoms

class Profil(models.Model):
    nom = models.CharField(max_length=254)
    def __str__(self):
        return self.nom

class Personnel(models.Model):
    nom = models.CharField(max_length=254)
    prenoms = models.CharField(max_length=254)
    adresse = models.CharField(max_length=254)
    num_compte = models.CharField(max_length=254)
    profil = models.ForeignKey(Profil, on_delete=models.CASCADE)
    def __str__(self):
        return self.nom +" "+ self.prenoms

class Client(models.Model):
    nom_client = models.CharField(max_length=254)
    prenom_client = models.CharField(max_length=254)
    num_compte = models.CharField(max_length=254)
    def __str__(self):
        return self.nom_client +' '+ self.prenom_client

class Fournisseur(models.Model):
    nom_four = models.CharField(max_length=254)
    tel_four = models.CharField(max_length=254)
    adresse_four = models.CharField(max_length=254)
    num_compte = models.CharField(max_length=254)
    def __str__(self):
        return self.nom_four

class Machine(models.Model):
    usage = models.CharField(max_length=254)
    responsable = models.ForeignKey(Personnel, on_delete=models.CASCADE)
    def __str__(self):
        return self.usage

class TypeMatiere(models.Model):
    nom = models.CharField(max_length=254)
    def __str__(self):
        return self.nom

class ProduitFini(models.Model):
    type_produit = models.CharField(max_length=254)
    def __str__(self):
        return self.type_produit

class Commande(models.Model):
    type_commande = models.CharField(max_length=254)
    date_commande = models.CharField(max_length=254)
    date_livr_commande = models.CharField(max_length=254, null =True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    def __str__(self):
        return self.num_commande

class Commercial(models.Model):
    num_agent_commer = models.CharField(max_length=254)
    def __str__(self):
        return self.num_commande

class ProduitCommande(models.Model):
    commande = models.ForeignKey(Commande, on_delete=models.CASCADE)
    produit = models.ForeignKey(ProduitFini, on_delete=models.CASCADE)
    quantite = models.IntegerField()
    def __str__(self):
        return self.num_commande

class Production(models.Model):
    produit = models.ForeignKey(ProduitFini, on_delete=models.CASCADE)
    quantite = models.IntegerField()
    date_production = models.CharField(max_length=254)
    def __str__(self):
        return self.produit.type_produit+ " ("+ self.quantite +")"

class Achat(models.Model):
    bois = models.ForeignKey(TypeMatiere, on_delete=models.CASCADE)
    fournisseur = models.ForeignKey(Fournisseur, on_delete=models.CASCADE)
    quantite = models.IntegerField()
    date_achat = models.CharField(max_length=254)
    def __str__(self):
        return self.bois.nom+ " ("+ self.quantite +")"

main_app/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponse 
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required 
import datetime
from django.contrib.auth.forms import UserCreationForm
from main_app.models import *
from main_app.forms import *
from django.http import JsonResponse
from django.core import serializers



@login_required
def commande_view(request):
	if request.method == "POST":
		form = CommandeForm(data=request.POST)
		if form.is_valid():
			instance = Commande()
			client_id= request.POST.get('client')
			client = Client.objects.get(id=client_id)
			instance.type_commande = request.POST.get('type_commande')
			instance.date_commande = request.POST.get('date_commande')
			instance.date_livr_commande = request.POST.get('date_livr_commande')
			instance.client= client
			instance.save()
		else :
			print(form.errors)

	else :
		form = CommandeForm()
	list_instances= Commande.objects.all()
	list_clients= Client.objects.all()

	return render(request,'main_app/commande_all.html', 
							{'list_instances':list_instances,
							'list_clients':list_clients,
							'form':form
							})
@login_required
def commande_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = Commande.objects.get(id=data_id) 
	instance.delete()
	return redirect('main_app:commande_view')

@login_required
def commande_produit_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = ProduitCommande.objects.get(id=data_id) 	
	commande_id= instance.commande.id
	instance.delete()
	return redirect('main_app:commande_detail_view',commande_id=commande_id )

@login_required
def commande_detail_view(request, commande_id):
	commande = Commande.objects.get(id=commande_id)
	list_instances= ProduitCommande.objects.filter(commande=commande_id)
	list_produits= ProduitFini.objects.all()
	form = ProduitCommandeForm()
	return render(request,'main_app/commande_detail.html', 
							{'commande':commande,
							 'list_instances':list_instances,
							 'list_produits':list_produits,
							 'form':form
							})


@login_required
def commande_produit_create_view(request):
	if request.method == "POST":
		form = ProduitCommandeForm(data=request.POST)
		commande_id = request.POST.get('commande_id')
		commande= Commande.objects.get(id=commande_id)
		if form.is_valid():
			instance = ProduitCommande()
			produit_id = request.POST.get('produit')
			produit = ProduitFini.objects.get(id=produit_id)
			instance.produit= produit
			instance.commande= commande
			instance.quantite = request.POST.get('quantite')
			instance.save()
		else :
			print(form.errors)

	else :
		form = ProduitCommandeForm()
	list_instances= ProduitCommande.objects.filter(commande=commande_id)
	list_produits= ProduitFini.objects.all()
	return render(request,'main_app/commande_detail.html', 
							{'commande':commande,
							 'list_instances':list_instances,
							 'list_produits':list_produits,
							 'form':form,
							})

@login_required
def commande_produit_edit_view(request):
	if request.method == "POST":
		form = ProduitCommandeForm(data=request.POST)
		if form.is_valid():
			id = request.POST.get('id')
			produit_id = request.POST.get('produit')
			produit = ProduitFini.objects.get(id=produit_id)
			instance = ProduitCommande.objects.get(id=id)
			instance.quantite = request.POST.get('quantite')
			instance.produit= produit
			instance.save()
			return redirect('main_app:commande_detail_view',commande_id=instance.commande.id )
		else :
			print('Form erros')

@login_required
def commande_edit_view(request):
	if request.method == "POST":
		commandeForm = CommandeForm(data=request.POST)
		if commandeForm.is_valid():
			id = request.POST.get('id')
			instance = Commande.objects.get(id=id)
			instance.type_commande = request.POST.get('type_commande')
			instance.date_commande = request.POST.get('date_commande')
			instance.date_livr_commande = request.POST.get('date_livr_commande')
			instance.save()
			return redirect('main_app:commande_view')
		else :
			print('Form erros')

@login_required
def achat_view(request):
	if request.method == "POST":
		form =AchatForm(data=request.POST)
		if form.is_valid():
			instance = Achat()
			bois_id= request.POST.get('bois')
			bois = TypeMatiere.objects.get(id=bois_id)
			fournisseur_id= request.POST.get('fournisseur')
			fournisseur = Fournisseur.objects.get(id=fournisseur_id)
			instance.quantite = request.POST.get('quantite')
			instance.date_achat = request.POST.get('date_achat')
			instance.bois = bois
			instance.fournisseur = fournisseur
			instance.save()
		else :
			print(form.errors)

	else :
		form = AchatForm()
	list_instances= Achat.objects.all()
	list_bois= TypeMatiere.objects.all()
	list_fournisseurs= Fournisseur.objects.all()

	return render(request,'main_app/achat_all.html', 
							{'list_instances':list_instances,
							'list_bois':list_bois,
							'list_fournisseurs':list_fournisseurs,
							'form':form
							})
@login_required
def achat_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = Achat.objects.get(id=data_id) 
	instance.delete()
	return redirect('main_app:achat_view')

@login_required
def achat_edit_view(request):
	if request.method == "POST":
		achatForm = AchatForm(data=request.POST)
		if achatForm.is_valid():
			id = request.POST.get('id')
			bois_id= request.POST.get('bois')
			bois = TypeMatiere.objects.get(id=bois_id)
			fournisseur_id= request.POST.get('fournisseur')
			fournisseur = Fournisseur.objects.get(id=fournisseur_id)
			instance = Achat.objects.get(id=id)
			instance.quantite = request.POST.get('quantite')
			instance.date_achat = request.POST.get('date_achat')
			instance.bois = bois
			instance.fournisseur = fournisseur
			instance.save()
			return redirect('main_app:achat_view')
		else :
			print('Form erros')

@login_required
def fournisseur_view(request):
	if request.method == "POST":
		form = FournisseurForm(data=request.POST)
		if form.is_valid():
			instance = Fournisseur()
			instance.nom_four = request.POST.get('nom_four')
			instance.tel_four = request.POST.get('tel_four')
			instance.adresse_four = request.POST.get('adresse_four')
			instance.num_compte = request.POST.get('num_compte')
			instance.save()
		else :
			print(form.errors)

	else :
		form = FournisseurForm()
	list_instances= Fournisseur.objects.all()

	return render(request,'main_app/fournisseur_all.html', 
							{'list_instances':list_instances,
							'form':form
							})
@login_required
def fournisseur_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = Fournisseur.objects.get(id=data_id) 
	instance.delete()
	return redirect('main_app:fournisseur_view')

@login_required
def fournisseur_edit_view(request):
	if request.method == "POST":
		fournisseurForm = FournisseurForm(data=request.POST)
		if fournisseurForm.is_valid():
			id = request.POST.get('id')
			instance = Fournisseur.objects.get(id=id)
			instance.nom_four = request.POST.get('nom_four')
			instance.tel_four = request.POST.get('tel_four')
			instance.adresse_four = request.POST.get('adresse_four')
			instance.num_compte = request.POST.get('num_compte')
			instance.save()
			return redirect('main_app:fournisseur_view')
		else :
			print('Form erros')


@login_required
def production_view(request):
	if request.method == "POST":
		form = ProductionForm(data=request.POST)
		if form.is_valid():
			instance = Production()
			produit_id= request.POST.get('produit')
			produit = ProduitFini.objects.get(id=produit_id)
			instance.quantite = request.POST.get('quantite')
			instance.date_production = request.POST.get('date_production')
			instance.produit = produit
			instance.save()
		else :
			print(form.errors)

	else :
		form = ProductionForm()
	list_instances= Production.objects.all()
	list_produits= ProduitFini.objects.all()

	return render(request,'main_app/production_all.html', 
							{'list_instances':list_instances,
							'list_produits':list_produits,
							'form':form
							})
@login_required
def production_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = Production.objects.get(id=data_id) 
	instance.delete()
	return redirect('main_app:production_view')

@login_required
def production_edit_view(request):
	if request.method == "POST":
		productionForm = ProductionForm(data=request.POST)
		if productionForm.is_valid():
			id = request.POST.get('id')
			produit_id= request.POST.get('produit')
			produit = ProduitFini.objects.get(id=produit_id)
			instance = Production.objects.get(id=id)
			instance.quantite = request.POST.get('quantite')
			instance.date_production = request.POST.get('date_production')
			instance.produit = produit
			instance.save()
			return redirect('main_app:production_view')
		else :
			print('Form erros')


@login_required
def bois_view(request):
	if request.method == "POST":
		form = TypeMatiereForm(data=request.POST)
		if form.is_valid():
			instance = TypeMatiere()
			instance.nom = request.POST.get('nom')
			instance.save()
		else :
			print(form.errors)

	else :
		form = TypeMatiereForm()
	list_instances= TypeMatiere.objects.all()

	return render(request,'main_app/bois_all.html', 
							{'list_instances':list_instances,
							'form':form
							})
@login_required
def bois_delete_view(request):
	data_id = request.POST.get('data_id')	
	instance = TypeMatiere.objects.get(id=data_id) 
	instance.delete()
	return redirect('main_app:bois_view')

@login_required
def bois_edit_view(request):
	if request.method == "POST":
		typeMatiereForm = TypeMatiereForm(data=request.POST)
		if typeMatiereForm.is_valid():
			id = request.POST.get('id')
			instance = TypeMatiere.objects.get(id=id)
			instance.nom = request.POST.get('nom')
			instance.save()
			return redirect('main_app:bois_view')
		else :
			print('Form erros')

@login_required

main_app/templates/main_app/layout/base.html
<!doctype html>
{% load static %}

<!-- {% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #} -->
{% load widget_tweaks %}         {# manage attr addinf to form field #}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="icon" type="image/png" href="{% static 'main_app/img/logo.png' %}">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

        <title>WoodApp</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>


        <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

          <!-- CSS Files -->
    <div>
    {% block css_content %}{% endblock %} 
    </div>

    <link href="{% static 'main_app/css/material-dashboard/material-dashboard.css' %}" rel="stylesheet" />
    <!-- <link href="{% static 'main_app/css/mystyle.css' %}" rel="stylesheet" /> -->

    <style type="text/css">
      
      .fit-image{
      width: 100%;
      object-fit: cover;
      /*height: 300px;*/ /* only if you want fixed height */
      }


    </style>

    </head>
  <body class="">
        <div class="wrapper">
    <div class="sidebar" data-color="green" data-background-color="black" data-image="{% static 'main_app/img/sidebar-1.jpg' %}">
      
      <div class="logo">
        <a href="" class="simple-text logo-mini">

        </a>
        <a href="" class="simple-text logo-normal">

        </a>
      </div>
      <div class="sidebar-wrapper">
        <div class="user pt-4">
          <div class="photo">
            <img src="{% static 'main_app/img/img_profile.png' %}" />
          </div>
          <div class="user-info">
            <a data-toggle="collapse" href="#collapseExample" class="username">
              <span>
                {{user.username}} 
                <b class="caret"></b>
              </span>
            </a>
            <div class="collapse" id="collapseExample">
              <ul class="nav">

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}" >
                       <span class="sidebar-mini"> SD </span> <span class="sidebar-normal"> Se déconnecter </span>
                    </a>
                  </li> 
              </ul>
            </div>
          </div>
        </div>
        <ul class="nav">
         <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:index' %}">
              <i class="material-icons">dashboard</i>
              <p> Tableau de bord </p>
            </a>
          </li> 
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:production_view' %}">
              <i class="material-icons">hourglass_full</i>
              <p> Production</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:achat_view' %}">
              <i class="material-icons">add_shopping_cart</i>
              <p> Achats</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:commande_view' %}">
              <i class="material-icons">shopping_bag</i>
              <p> Commandes</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:client_view' %}">
              <i class="material-icons">admin_panel_settings</i>
              <p> Clients </p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:profil_view' %}">
              <i class="material-icons">api</i>
              <p> Profils </p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:personnel_view' %}">
              <i class="material-icons">people</i>
              <p> Personnels </p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:produit_view' %}">
              <i class="material-icons">graphic_eq</i>
              <p> Produits </p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:machine_view' %}">
              <i class="material-icons">build</i>
              <p> Machines </p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:bois_view' %}">
              <i class="material-icons">view_stream</i>
              <p> Type de bois </p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'main_app:fournisseur_view' %}">
              <i class="material-icons">perm_contact_calendar</i>
              <p> Fournisseurs</p>
            </a>
          </li> 
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'accounts:user_view' %}">
              <i class="material-icons">people</i>
              <p> Utilisateurs</p>
            </a>
          </li>              
        </ul>
      </div>
    </div>
    <div class="main-panel">

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top " id="navigation-example">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-minimize">
              <button id="minimizeSidebar" class="btn btn-just-icon btn-white btn-fab btn-round">
                <i class="material-icons text_align-center visible-on-sidebar-regular">more_vert</i>
                <i class="material-icons design_bullet-list-67 visible-on-sidebar-mini">view_list</i>
              </button>
            </div>
            <a class="navbar-brand" href="">
               WoodApp
            </a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation" data-target="#navigation-example">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            
            <ul class="navbar-nav">
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">  
          {% block content %}{% endblock %} 
        </div>
      </div>
    </div>

  </div>
 
    


      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">        


    {% block content1 %}{% endblock %} 
        </div>
      </div>
 


  <!--   Core JS Files   -->
  <script src="{% static 'main_app/js/jquery.min.js' %}" ></script>
  <script src="{% static 'main_app/js/popper.min.js' %}" ></script>
  <script src="{% static 'main_app/js/material-dashboard/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>

  <script src="{% static 'main_app/js/selectFilter.min.js' %}" ></script>

  <div>
    {% block js_content %}{% endblock %} 
  </div>

  <script src="{% static 'main_app/js/material-dashboard/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!-- Plugin for the momentJs  -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/moment.min.js' %}"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/sweetalert2.js' %}"></script>
  <!-- Forms Validations Plugin -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/jquery.validate.min.js' %}"></script>
  <!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/jquery.bootstrap-wizard.js' %}"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/bootstrap-selectpicker.js' %}"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/bootstrap-datetimepicker.min.js' %}"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/jquery.dataTables.min.js' %}"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/bootstrap-tagsinput.js' %}"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/jasny-bootstrap.min.js' %}"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/fullcalendar.min.js' %}"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/jquery-jvectormap.js' %}"></script>

  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/nouislider.min.js' %}"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
  <!-- Library for adding dinamically elements -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/arrive.min.js' %}"></script>

  <!-- Chartist JS -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/chartist.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'main_app/js/material-dashboard/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'main_app/js/material-dashboard/material-dashboard.min.js' %}" ></script>
  <script src="{% static 'main_app/js/demo.js' %}"></script>



  <script>
    $(document).ready(function() { 

      md.initFormExtendedDatetimepickers();
      md.initVectorMap();

    });
  </script>
</body>

</html>