accounts/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.urls import path 

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('users/delete', views.user_delete_view, name='user_delete_view'),
    path('users/', views.user_view, name='user_view'),
]

woodapp_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path
from main_app import views as main_app_views 
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls), 
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^', include('main_app.urls')),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ["first_name","last_name","username", "email", "password1", "password2"]

accounts/views.py
# views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.models import User


# Create your views here.

@login_required
def user_view(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
	        form.save()
        return redirect("accounts:user_view")
    else:
        form = RegisterForm()
    list_instances= User.objects.all()

    return render(request, "accounts/user_all.html", 
            {"form":form,
            "list_instances":list_instances
            })

@login_required
def user_delete_view(request):
	data_id = request.POST.get('data_id')		
	instance = User.objects.get(id=data_id) 
	instance.delete()
	return redirect('accounts:user_view')

@login_required
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
	        form.save()
        return redirect("accounts:user_view")
    else:
        form = RegisterForm()

    return render(request, "registration/signup.html", {"form":form})

accounts/templates/accounts/user_all.html
{% extends 'main_app/layout/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="bg-white mb-5 pb-5 mt-2">
<div class="row mt-2 pt-2 m-2">
	<div class="col-sm-8">
		<h2>Gestion des Utilisateurs</h2>
	</div>
	<div class="col-sm-4">
		<button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#additem"  >Nouvel Utilisateur</button>
	</div>
</div>	 
<div class="row justify-content-center m-1    ">
	 <div class="col-sm-12 table-responsive">
	 	<table class="table table-bordered">
		  <thead class="bg-dark text-white">
		    <tr> 
		      <!-- <th scope="col">#</th> -->
		      <th scope="col">Nom & Prénom   </th>
		      <th scope="col">Email   </th>
		      <th scope="col" class="text-right">Actions</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for item in list_instances %}

		    <tr> 
		      <td>{{ item.last_name }}  {{ item.first_name }}</td>
		      <td>{{ item.email }}</td>
		      <td class="text-right">
				{% comment %} <a href="#" rel="tooltip" class="btn btn-info btn-sm btn-round" data-toggle="modal" data-target="#edit_item_{{item.id}}" >
					                    <i class="material-icons">edit</i>
				</a> {% endcomment %}


					                
				<button type="button" rel="tooltip" class="btn btn-danger btn-sm btn-round"  onclick="event.preventDefault();
                              document.getElementById('form_item_{{item.id}}').submit();" >
					                    <i class="material-icons">close</i>
				</button>
					                
                <form id="form_item_{{item.id}}" action="{% url 'accounts:user_delete_view' %}" method="POST" style="display: none;">
                                        {% csrf_token %} 
                                        <input type="text" hidden class="form-control"  name="data_id" value="{{item.id}}" >
                </form>      	 
		      </td> 
		    </tr>  

		    {% endfor %}
		  </tbody>
		</table>
	 </div> 

</div>
</div>





<div class="modal fade" id="additem" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ajout d'un utilisateur</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'accounts:user_view' %}" method="POST"  >
		    {% csrf_token %}                 
            {{ form|crispy }}
		    <div class="row mt-1 pt-1">
		    	<div class="col-sm-4">
		    		
        			<button type="submit" class="btn btn-info">Enregistrer</button>
		    	</div>
		    </div>


		</form>
      </div> 
    </div>
  </div>
</div>


{% endblock %}